<fieldset style='width:450px;'>
<legend>Créer un script à partir d'une table</legend>
<form name='myForm' method='POST' action=''>
	<input type='hidden' name='userdb' value='<phx:echo var="userdb" />'>
	<input type='hidden' name='usertable' value='<phx:echo var="usertable" />'>
	<input type='hidden' name='dbgrid' value='<phx:echo var="dbgrid" />'>
	<input type='hidden' name='menu' value='<phx:echo var="menu" />'>
	<input type='hidden' name='filter' value='<phx:echo var="filter" />'>
	<input type='hidden' name='addoption' value='<phx:echo var="addoption" />'>
	<input type='hidden' name='me_id' value='<phx:echo var="me_id" />'>
	<input type='hidden' name='me_level' value='<phx:echo var="me_level" />'>
	<input type='hidden' name='bl_id' value='<phx:echo var="bl_id" />'>
	<input type='hidden' name='pa_filename' value='<phx:echo var="pa_filename" />'>
	<input type='hidden' name='extension' value='<phx:echo var="extension" />'>
	<input type='hidden' name='basedir' value='<phx:echo var="basedir" />'>
	<input type='hidden' name='di_name' value='<phx:echo var="di_name" />'>
	<input type='hidden' name='di_long' value='<phx:echo var="di_long" />'>
	<input type='hidden' name='di_short' value='<phx:echo var="di_short" />'>
	<input type='hidden' name='autogen' value='<phx:echo var="autogen" />'>
	<input type='hidden' name='pz_current_tab' value=''>

	<table border='0' bordercolor='0' width='85%' valign='top' style='display:hidden;'>
	<tr><td>
	<table border='0' cellspacing='0' cellpadding='0'>
	<tr><td>Nom</td>
	<td>Taille DB</td>
	<td>Type DB</td>
	<td>Type HTML</td>
	<td>Largeur</td>
	<td>Hauteur</td>
	</tr>
	<?php
	foreach ($this->field_defs as $def) {
		$this->defs = explode(",", $def);
		?><tr><?php
		$this->options = $this->datacontrols->createOptionsFromArray($this->list, ",", 0, 0, [], $this->defs[3], false);
		?>
		<td><input type='text' size='25' value='<phx:echo var="defs[0]" />'></td>
		<td><input type='text' readonly size='10' value='<phx:echo var="defs[1]" />'></td>
		<td><input type='text' readonly size='10' value='<phx:echo var="defs[2]" />'></td>
		<td><select name='<phx:echo var="defs[3]" />'><phx:echo var="options['list']" /></select></td>
		<td><input type='text' size='5' value='<phx:echo var="defs[4]" />'></td>
		<td><input type='text' size='5' value='<phx:echo var="defs[5]" />'></td>
		</tr>
		<?php
	}
	?>
	</table>
	</td></tr>
	<tr><td colspan='3' align='center'>
	<br><input type='button' name='previous' value='<< Précédent' onClick='document.myForm.action="admin?di=mkscript&lg=<phx:echo var="lg" />";document.myForm.submit()'>
	&nbsp;<input type='button' name='next' value='Suivant >>' onClick='document.myForm.action="admin?di=mkfile&lg=<phx:echo var="lg" />";document.myForm.submit()'>
	</td></tr>
	</table>


</form>
</fieldset>
