<!--script type='text/javascript' src='<phx:echo var="script" />' ></script-->
<table border='0' cellspacing='0' cellpadding='0'>
<tr class="Row0">
    <td width='100%' align='center' valign='bottom'>
        <a onclick='TPager.leftLimit()' href='javascript:void(0)'><img src='<phx:exec type="\Phink\Web\TWebApplication" stmt="imagePath" />/scroll/leftLimit_0.gif' valign='top' border='0'></a>
        <a onclick='TPager.fastLeft()' href='javascript:void(0)'><img src='<phx:exec type="\Phink\Web\TWebApplication" stmt="imagePath" />/scroll/fastLeft_0.gif' valign='top' border='0'></a>
        <phx:echo var="pageCount" /> <phx:echo var="caption" /> - Page <span id='<phx:echo var="id" />pageNum' ><phx:echo var="pageNum" /></span>
        <a onclick='TPager.fastRight()' href='javascript:void(0)'><img src='<phx:exec type="\Phink\Web\TWebApplication" stmt="imagePath" />/scroll/fastRight_0.gif' valign='top' border='0'></a>
        <a onclick='TPager.rightLimit()' href='javascript:void(0)'><img src='<phx:exec type="\Phink\Web\TWebApplication" stmt="imagePath" />/scroll/rightLimit_0.gif' valign='top' border='0'></a>
    </td>
</tr>
</table>
