version: "3.0"
services:
  php:
    build: ./docker
    image: lap:phink
    ports:
     - '8080:80'
     - '8443:443'
    volumes:
     - ./src:/sites/portable/src
     - ./vendor:/sites/portable/vendor
     - ./framework:/sites/portable/framework


