version: "3.0"
services:
  aphpache:
    build: ./docker
    image: lap:phink
    ports:
     - '80:80'
     - '443:443'
    volumes:
      - .:/Sites/CodePhoenixOrg/SDK/php/Phink
      - ../Reed:/Sites/CodePhoenixOrg/SDK/php/Reed
      - ../../javascript/PhinkJS:/Sites/CodePhoenixOrg/SDK/javascript/PhinkJS