<html debug="true" lang="en">
<head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <title>Console</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <meta name="description" content="">
    <meta name="author" content="">

    <link href="/css/_3rdparty.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=PT+Mono" rel="stylesheet">
    <script type="text/javascript" 
            data-depends="/js/_3rdparty.js" 
            src="/phink.js">
    </script>

</head>
<body>
    <h1>
        <pre>
 ____  _     _       _
|  _ \| |__ (_)_ __ | | __  ___  _ __ __ _
| |_) | '_ \| | '_ \| |/ / / _ \| '__/ _` |
|  __/| | | | | | | |   < | (_) | | | (_| |
|_|   |_| |_|_|_| |_|_|\_(_)___/|_|  \__, |
                                     |___/
        </pre>
    </h1>
    <h2>
    Console
    </h2>
    <phx:TConsoleWindow id="console0"  />
</body>
</html>