<html class="ibm-pc" lang="en">
<head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <title>Console</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <meta name="description" content="">
    <meta name="author" content="">

    <!-- <link href="/css/_3rdparty.css" rel="stylesheet"> -->
    <!-- <link href="https://fonts.googleapis.com/css?family=PT+Mono" rel="stylesheet"> -->
    <script type="text/javascript" 
            data-depends="/js/_3rdparty.js" 
            src="/phink.js">
    </script>

</head>
<body >
    <div id="basics">
        Basics&nbsp; 
        <button id="rlog" >Clear logs</button>
    </div>
    <div id="themes">
        Themes&nbsp; 
        <button id="ibm-pcTheme" >IBM-PC</button>
        <button id="amstrad-cpcTheme" >AMSTRAD CPC</button>
        <button id="solarisTheme" >Solaris</button>
    </div>
    <h3 id="logo">
        <pre>
 ____  _     _       _
|  _ \| |__ (_)_ __ | | __
| |_) | '_ \| | '_ \| |/ /
|  __/| | | | | | | |   < 
|_|   |_| |_|_|_| |_|_|\_\
    Think ${PHP} Different 
    
© 2019 David Blanchard                                
        </pre>
    </h3>
    <h3>
    Console
    </h3>
    <div id="result">
    </div>
    <phx:TConsoleWindow id="console0"  />
</body>
</html>