<html debug="true" lang="en">
<head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <title>Console</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <meta name="description" content="">
    <meta name="author" content="">

</head>
<body>
<pre>
<!--  text="prop:result" -->
<phx:TConsoleWindow id="console0"  />
</pre>

</body>
</html>