<html class="theme" lang="en">
<head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <title><phx:echo var="qbeTitle" /></title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <meta name="description" content="">
    <meta name="author" content="">
    <link href="<phx:echo const="REWRITE_BASE" />fonts/fontawesome-webfont.woff2" rel="stylesheet">

    <!-- <link href="https://fonts.googleapis.com/css?family=PT+Mono" rel="stylesheet"> -->
    <script type="text/javascript" 
            data-depends="<phx:echo const="REWRITE_BASE" />js/_3rdparty.js" 
            src="<phx:echo const="REWRITE_BASE" />phink.js">
    </script>

</head>
<body >
    <div id="basics">
        Basics&nbsp; 
        <button id="rlog" >Clear logs</button>&nbsp;
    </div>
    <div id="themes">
        Themes&nbsp; 
        <button id="ibm-pcTheme" >IBM-PC</button>
        <button id="amstrad-cpcTheme" >AMSTRAD CPC</button>
        <button id="solarisTheme" >Solaris</button>
    </div>
    <h3 id="logo">
        <pre>
 ____  _     _       _
|  _ \| |__ (_)_ __ | | __
| |_) | '_ \| | '_ \| |/ /
|  __/| | | | | | | |   < 
|_|   |_| |_|_|_| |_|_|\_\
    Think ${PHP} Different 
    
© 2019 David Blanchard                                
        </pre>
    </h3>
    <h3>
    Query By Example
    </h3>
    
    <div id="result">
    </div>
    <phx:TQbeWindow id="qbe0" />
    <script>
        var qbe = null;
        var qbeHost = window.location.hostname + '<phx:echo const="REWRITE_BASE" />';
        var qbeName = '<phx:echo var="qbeName" />'
        document.querySelector(':root').style.setProperty('--back-color', '<phx:echo var="themeBackColor" />');
        document.querySelector(':root').style.setProperty('--fore-color', '<phx:echo var="themeForeColor" />');
    </script>
</body>
</html>