<?php
$pc = getArgument("pc");
$sr = getArgument("sr");
$curl_pager = "";
$dialog = "";
if(isset($pc)) $curl_pager="&pc=$pc";
if(isset($sr)) $curl_pager.="&sr=$sr";
if($this->query === "SELECT") {
    $sql = <<<SQL
    SELECT 
        di_id, di_name as 'Clé', di_fr_short as 'Libellé court', di_fr_long as 'Libellé long'
    FROM
        dictionary
SQL;
    $dbgrid = $this->datacontrols->createPagerDbGrid('dictionary', $sql, $this->page_id, "", "&query=ACTION$curl_pager", "", true, true, $dialog, [0, 50, 200, 300], 15, $this->grid_colors, $this->cs);
    echo "<br>".$dbgrid;
} elseif($this->query === "ACTION") {
?>
<form method="POST" name="dictionaryForm" action="?id=21&lg=fr">
<input type="hidden" name="query" value="ACTION">
<input type="hidden" name="event" value="onRun">
<input type="hidden" name="pc" value="<?php echo $pc?>">
<input type="hidden" name="sr" value="<?php echo $sr?>">
<input type="hidden" name="di_id" value="<?php echo $this->di_id?>">
<table border="1" bordercolor="<?php echo $this->panel_colors->border_color?>" cellpadding="0" cellspacing="0" witdh="100%" height="1">
<tr>
    <td align="center" valign="top" bgcolor="<?php echo $this->panel_colors->back_color?>">
        <table>
            <tr>
                <td>di_id</td>
                <td>
                    <?php echo $this->di_id?>
                </td>
            </tr>
            <tr>
                <td>di_name</td>
                <td>
                    <textarea name="di_name" cols="80" rows="8"><?php echo $this->di_name?></textarea>
                </td>
            </tr>
            <tr>
                <td>di_fr_short</td>
                <td>
                    <textarea name="di_fr_short" cols="80" rows="8"><?php echo $this->di_fr_short?></textarea>
                </td>
            </tr>
            <tr>
                <td>di_fr_long</td>
                <td>
                    <textarea name="di_fr_long" cols="80" rows="8"><?php echo $this->di_fr_long?></textarea>
                </td>
            </tr>
            <tr>
                <td>di_en_short</td>
                <td>
                    <textarea name="di_en_short" cols="80" rows="8"><?php echo $this->di_en_short?></textarea>
                </td>
            </tr>
            <tr>
                <td>di_en_long</td>
                <td>
                    <textarea name="di_en_long" cols="80" rows="8"><?php echo $this->di_en_long?></textarea>
                </td>
            </tr>
            <tr>
                <td>di_ru_short</td>
                <td>
                    <textarea name="di_ru_short" cols="80" rows="8"><?php echo $this->di_ru_short?></textarea>
                </td>
            </tr>
            <tr>
                <td>di_ru_long</td>
                <td>
                    <textarea name="di_ru_long" cols="80" rows="8"><?php echo $this->di_ru_long?></textarea>
                </td>
            </tr>
            <tr>
                <td align="center" colspan="2">
                    <input type="submit" name="action" value="<?php echo $this->action?>">
                    <?php   if($this->action!="Ajouter") { ?>
                    <input type="submit" name="action" value="Supprimer">
                    <?php   } ?>
                    <input type="reset" name="action" value="Annuler">
                    <input type="submit" name="action" value="Retour">
                </td>
            </tr>
        </table>
        </td>
    </tr>
</table>
</form>
<?php
}
?>