<div class="step" >
	<form method='post' name='myTabForm'>
		<fieldset style='width:450px'>
		<legend>Créer un script, un menu, un bloc ...</legend>
		<table border='0' bordercolor='0' width='85%' valign='top' >
		<tr><td>&nbsp;</td><td>
		<input type='radio'<phx:echo var="rad_choice[0]" /> name='choice' value='mkscript'>Auto-générer un script à partir d'une table<br>
		<input type='radio'<phx:echo var="rad_choice[1]" /> name='choice' value='mkmenus'>Créer une nouvelle entrée de menu<br>
		<input type='radio'<phx:echo var="rad_choice[2]" /> name='choice' value='mkblock'>Créer un nouveau bloc&nbsp;
		</td><td>&nbsp;</td></tr>
		<tr><td colspan='2' align='center'>
		<br><input type='button' name='action' value='Suivant >>' onclick='<phx:echo var="on_click" />'>
		</td></tr>
		</table>
		</fieldset>

		<phx:echo var="tab_start" />
	</form>
</div>