<?php
$pc = getArgument("pc");
$sr = getArgument("sr");
$curl_pager = "";
$dialog = "";
if(isset($pc)) $curl_pager="&pc=$pc";
if(isset($sr)) $curl_pager.="&sr=$sr";
if($this->query === "SELECT") {
    $sql = <<<SQL
		SELECT
			me_id,
			d.di_fr_short AS 'Entrée',
			CASE
				WHEN me_level = '0' THEN 'Caché'
				WHEN me_level = '1' THEN 'Principal'
				WHEN me_level = '2' THEN 'Latéral'
			END AS Niveau,
			bd.di_fr_short AS Bloc
		FROM
			menus m
				INNER JOIN
			pages p ON m.pa_id = p.pa_id
				INNER JOIN
			dictionary d ON d.di_id = p.di_id
				LEFT JOIN
			blocks b ON m.bl_id = b.bl_id
				LEFT OUTER JOIN
			dictionary bd ON bd.di_id = b.di_id
		ORDER BY d.di_fr_short
		SQL;
    $dbgrid = $this->datacontrols->createPagerDbGrid('menus', $sql, $this->page_id, "admin", "&query=ACTION$curl_pager", "", true, true, $dialog, [0, 400], 15, $this->grid_colors, $this->cs);
    echo "<br>".$dbgrid;
} elseif($this->query === "ACTION") {
?>
<form method="POST" name="menusForm" action="admin?id=18&lg=fr">
<input type="hidden" name="query" value="ACTION">
<input type="hidden" name="event" value="onRun">
<input type="hidden" name="pc" value="<?php echo $pc?>">
<input type="hidden" name="sr" value="<?php echo $sr?>">
<input type="hidden" name="me_id" value="<?php echo $this->me_id?>">
<table border="1" bordercolor="<?php echo $this->panel_colors->border_color?>" cellpadding="0" cellspacing="0" witdh="100%" height="1">
<tr>
    <td align="center" valign="top" bgcolor="<?php echo $this->panel_colors->back_color?>">
        <table>
            <tr>
                <td>me_id</td>
                <td>
                    <?php echo $this->me_id?>
                </td>
            </tr>
            <tr>
                <td>me_level</td>
                <td>
                    <textarea name="me_level" cols="80" rows="8"><?php echo $this->me_level?></textarea>
                </td>
            </tr>
            <tr>
                <td>me_target</td>
                <td>
                    <textarea name="me_target" cols="80" rows="8"><?php echo $this->me_target?></textarea>
                </td>
            </tr>
            <?php
            $sql = "select pa_id, bl_id from __page_block order by bl_id";
            $options = $this->datacontrols->createOptionsFromQuery($sql, 0, 1, [], $this->pa_id, false, $this->cs);
            ?>
            <tr>
                <td>pa_id</td>
                <td>
                    <select name="pa_id">
                    <?php echo $options["list"]; ?>
                    </select>
                </td>
            </tr>
            <?php
            $sql = "select bl_id, bl_column from blocks order by bl_column";
            $options = $this->datacontrols->createOptionsFromQuery($sql, 0, 1, [], $this->bl_id, false, $this->cs);
            ?>
            <tr>
                <td>bl_id</td>
                <td>
                    <select name="bl_id">
                    <?php echo $options["list"]; ?>
                    </select>
                </td>
            </tr>
            <tr>
                <td align="center" colspan="2">
                    <input type="submit" name="action" value="<?php echo $this->action?>">
                    <?php   if($this->action!="Ajouter") { ?>
                    <input type="submit" name="action" value="Supprimer">
                    <?php   } ?>
                    <input type="reset" name="action" value="Annuler">
                    <input type="submit" name="action" value="Retour">
                </td>
            </tr>
        </table>
        </td>
    </tr>
</table>
</form>
<?php
}
?>