<?php
$pc = getArgument("pc");
$sr = getArgument("sr");
$curl_pager = "";
$dialog = "";
if(isset($pc)) $curl_pager="&pc=$pc";
if(isset($sr)) $curl_pager.="&sr=$sr";
if($this->query === "SELECT") {
    $sql = <<<SQL
    select pa_id, d.di_fr_short as 'Page', pa_filename as 'Fichier' 
        from pages p
            inner join dictionary d on p.di_id = d.di_id
        order by pa_id
    SQL;
    $dbgrid = $this->datacontrols->createPagerDbGrid('pages', $sql, $this->page_id, "admin", "&query=ACTION$curl_pager", "", true, true, $dialog, [0, 300, 200], 15, $this->grid_colors, $this->cs);
    echo "<br>".$dbgrid;
} elseif($this->query === "ACTION") {
?>
<form method="POST" name="pagesForm" action="admin?id=19&lg=fr">
<input type="hidden" name="query" value="ACTION">
<input type="hidden" name="event" value="onRun">
<input type="hidden" name="pc" value="<?php echo $pc?>">
<input type="hidden" name="sr" value="<?php echo $sr?>">
<input type="hidden" name="pa_id" value="<?php echo $this->pa_id?>">
<table border="1" bordercolor="<?php echo $this->panel_colors->border_color?>" cellpadding="0" cellspacing="0" witdh="100%" height="1">
<tr>
    <td align="center" valign="top" bgcolor="<?php echo $this->panel_colors->back_color?>">
        <table>
            <tr>
                <td>pa_id</td>
                <td>
                    <?php echo $this->pa_id?>
                </td>
            </tr>
            <tr>
                <td>pa_filename</td>
                <td>
                    <textarea name="pa_filename" cols="80" rows="8"><?php echo $this->pa_filename?></textarea>
                </td>
            </tr>
            <tr>
                <td>pa_directory</td>
                <td>
                    <textarea name="pa_directory" cols="80" rows="8"><?php echo $this->pa_directory?></textarea>
                </td>
            </tr>
            <tr>
                <td>pa_url</td>
                <td>
                    <textarea name="pa_url" cols="80" rows="8"><?php echo $this->pa_url?></textarea>
                </td>
            </tr>
            <?php
            $sql = "select di_id, di_name from dictionary order by di_name";
            $options = $this->datacontrols->createOptionsFromQuery($sql, 0, 1, [], $this->di_id, false, $this->cs);
            ?>
            <tr>
                <td>di_id</td>
                <td>
                    <select name="di_id">
                    <?php echo $options["list"]; ?>
                    </select>
                </td>
            </tr>
            <?php
            $sql = "select ft_id, ft_type from _page_type order by ft_type";
            $options = $this->datacontrols->createOptionsFromQuery($sql, 0, 1, [], $this->ft_id, false, $this->cs);
            ?>
            <tr>
                <td>ft_id</td>
                <td>
                    <select name="ft_id">
                    <?php echo $options["list"]; ?>
                    </select>
                </td>
            </tr>
            <?php
            $sql = "select app_id, doc_id from __app_document order by doc_id";
            $options = $this->datacontrols->createOptionsFromQuery($sql, 0, 1, [], $this->app_id, false, $this->cs);
            ?>
            <tr>
                <td>app_id</td>
                <td>
                    <select name="app_id">
                    <?php echo $options["list"]; ?>
                    </select>
                </td>
            </tr>
            <tr>
                <td align="center" colspan="2">
                    <input type="submit" name="action" value="<?php echo $this->action?>">
                    <?php   if($this->action!="Ajouter") { ?>
                    <input type="submit" name="action" value="Supprimer">
                    <?php   } ?>
                    <input type="reset" name="action" value="Annuler">
                    <input type="submit" name="action" value="Retour">
                </td>
            </tr>
        </table>
        </td>
    </tr>
</table>
</form>
<?php
}
?>