<phx:element id="table" pattern="<table %s >{} </table>" rule="/<table (.*)[^>]>(.*)[^<]<\/table>/U" />
<phx:element id="table" pattern="<thead >{} </thead>" rule="/<thead (.*)[^>]>(.*)[^<]<\/thead>/U" />
<phx:element id="table" pattern="<tbody >{} </tbody>" rule="/<tbody (.*)[^>]>(.*)[^<]<\/tbody>/U" />
<phx:element id="table" pattern="<tr %s >{} </tr>" rule="/<tr (.*)[^>]>/U" />
<phx:element id="table" pattern="<th %s >{} </th>" rule="/<th >(&nbsp;)[^<]<\/th>/U" />
<phx:element id="table" pattern="<td %s >{} </td>" rule="/<td >(&nbsp;)[^<]<\/td>/U" />
<phx:element id="ulli" pattern="<ul %s >{} </ul>" rule="/<ul (.*)[^>]>/U" />
<phx:element id="ulli" pattern="<li %s >{} </li>" rule="/<li (.*)[^>]>(.*)[^<]<\/li>/U" />
<phx:element id="ulli" pattern="<div %s >{} </div>" rule="/<div (.*)[^>]>(.*)[^<]<\/div>/U" />
<phx:element id="olli" pattern="<ol %s >{} </ol>" rule="/<ol (.*)[^>]>(.*)[^<]<\/ol>/U" />
<phx:element id="olli" pattern="<li %s >{} </li>" rule="/<li (.*)[^>]>(.*)[^<]<\/li>/U" />
<phx:element id="olli" pattern="<div %s >{} </div>" rule="/<div (.*)[^>]>(.*)[^<]<\/div>/U" />
<phx:element id="accordion" pattern="<div class='accordion %s ui-accordion ui-widget' >{} </div>" rule="/<div (.*)[^>]>(.*)[^<]<\/div>/U" />
<phx:element id="accordion" pattern="<h3 class='ui-accordion-header ui-state-active ui-accordion-header-active' ><span class='ui-icon ui-accordion-header-icon ui-icon-minusthick'></span>{} </h3>" rule="/<h3 (.*)[^>]>(.*)[^<]<\/h3>/U" />
<phx:element id="accordion" pattern="<div class='content ui-widget-content ui-accordion-content-active' >{} </div>" rule="/<div (.*)[^>]>(.*)[^<]<\/div>/U" />
<phx:element id="list" pattern="<div class='list' >{} </div>" rule="/<div (.*)[^>]>(.*)[^<]<\/div>/U" />
<phx:element id="list" pattern="<div class='list-header' ><span class='list-icon'></span>{} </div>" rule="/<h3 (.*)[^>]>(.*)[^<]<\/h3>/U" />
<phx:element id="list" pattern="<div class='list-content' >{} </div>" rule="/<div (.*)[^>]>(.*)[^<]<\/div>/U" />
