<div>
    <div class="clear">
        <span>Query to test</span>    <button id="sendQuery" >Submit</button>
    <div>
    <div id="sql" class="float">
        <textarea name="query" id="query"  cols="80" rows="24"></textarea>
    </div>
    <div id="recordset" class="float">
        <pre >

        </pre>
    </div>

</div>
<div  class="clear">
<pre>
<phx:echo var="args" />
</pre>
<pre>
<phx:echo var="text" />
</pre>
</div>