<phx:element id="accordion" pattern="<div class='accordion %s ui-accordion ui-widget' >{} </div>" rule="/<div (.*)[^>]>(.*)[^<]<\/div>/U" />
<phx:element id="accordion" pattern="<h3 class='ui-accordion-header ui-state-active ui-accordion-header-active' ><span class='ui-icon ui-accordion-header-icon ui-icon-minusthick'></span>{} </h3>" rule="/<h3 (.*)[^>]>(.*)[^<]<\/h3>/U" />
<phx:element id="accordion" pattern="<div class='content ui-widget-content ui-accordion-content-active' >{} </div>" rule="/<div (.*)[^>]>(.*)[^<]<\/div>/U" />
