<!--script type='text/javascript' src='<phx:echo var="script" />' ></script-->
<table id='<phx:echo var="forThis" />Pager' border='0' cellspacing='0' cellpadding='0'>
<tr class="Row0">
    <td width='100%' align='center' valign='bottom'>
        <a onclick='<phx:echo var="forThis" />Pager.leftLimit()' href='javascript:void(0)'>
            <span><<</span>
        </a>
        <a onclick='<phx:echo var="forThis" />Pager.fastLeft()' href='javascript:void(0)'>
            <span><</span>
        </a>
        <phx:echo var="pageCount" /> <phx:echo var="caption" /> - Page 
        <span id='<phx:echo var="id" />pageNum' >
           <phx:echo var="pageNum" />
        </span>
        <a onclick='<phx:echo var="forThis" />Pager.fastRight()' href='javascript:void(0)'>
            <span>></span>
        </a>
        <a onclick='<phx:echo var="forThis" />Pager.rightLimit()' href='javascript:void(0)'>
            <span>>></span>
        </a>
    </td>
</tr>
</table>
