<html lang="en">
<head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <title>Welcome to the Phink framework</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <meta name="description" content="">
    <meta name="author" content="">

    <!-- <link href="/css/_3rdparty.css" rel="stylesheet"> -->
    <!-- <link href="https://fonts.googleapis.com/css?family=PT+Mono" rel="stylesheet"> -->
    <script type="text/javascript" 
            data-depends="<phx:echo const="REWRITE_BASE" />js/_3rdparty.js" 
            src="<phx:echo const="REWRITE_BASE" />phink.js">
    </script>

</head>
<body >
    <h3 id="logo">
        <pre>
 ____  _     _       _
|  _ \| |__ (_)_ __ | | __
| |_) | '_ \| | '_ \| |/ /
|  __/| | | | | | | |   < 
|_|   |_| |_|_|_| |_|_|\_\
    Think ${PHP} Different 
    
© 2019 David Blanchard                                  
        </pre>
    </h3>
    <h3>
    Learn to make your first page
    </h3>
    <p>
        You can find basic tools on the&nbsp;
        <a href="<phx:echo const="REWRITE_BASE" />admin/console">console</a>
    </p>
    <p>
        You can find admin tools on the&nbsp;
        <a href="<phx:echo const="REWRITE_BASE" />admin">administration interface</a>
    </p>
    <p>
        You can query the porject database on the&nbsp;
        <a href="<phx:echo const="REWRITE_BASE" />admin/qbe">SQL editor interface</a>
    </p>
</body>
</html>