<?php
$pc = getArgument("pc");
$sr = getArgument("sr");
$curl_pager = "";
$dialog = "";
if(isset($pc)) $curl_pager="&pc=$pc";
if(isset($sr)) $curl_pager.="&sr=$sr";
if($this->query === "SELECT") {
    $sql = "select br_id, br_title from bugreport order by br_id";
    $dbgrid = $this->datacontrols->createPagerDbGrid('bugreport', $sql, $this->page_id, "page.html", "&query=ACTION$curl_pager", "", true, true, $dialog, [0, 400], 15, $this->grid_colors, $this->cs);
    echo "<br>".$dbgrid;
} elseif($this->query === "ACTION") {
?>
<form method="POST" name="bugreportForm" action="page.html?id=26&lg=fr">
<input type="hidden" name="query" value="ACTION">
<input type="hidden" name="event" value="onRun">
<input type="hidden" name="pc" value="<?php echo $pc?>">
<input type="hidden" name="sr" value="<?php echo $sr?>">
<input type="hidden" name="br_id" value="<?php echo $this->br_id?>">
<table border="1" bordercolor="<?php echo $this->panel_colors->border_color?>" cellpadding="0" cellspacing="0" witdh="100%" height="1">
<tr>
    <td align="center" valign="top" bgcolor="<?php echo $this->panel_colors->back_color?>">
        <table>
            <tr>
                <td>br_id</td>
                <td>
                    <?php echo $this->br_id?>
                </td>
            </tr>
            <tr>
                <td>br_title</td>
                <td>
                    <textarea name="br_title" cols="80" rows="8"><?php echo $this->br_title?></textarea>
                </td>
            </tr>
            <tr>
                <td>br_text</td>
                <td>
                    <textarea name="br_text" cols="80" rows="8"><?php echo $this->br_text?></textarea>
                </td>
            </tr>
            <tr>
                <td>br_importance</td>
                <td>
                    <input type="text" name="br_importance" size="80" value="<?php echo $this->br_importance?>">
                </td>
            </tr>
            <tr>
                <td>br_date</td>
                <td>
                    <input type="text" name="br_date" size="80" value="<?php echo $this->br_date?>">
                </td>
            </tr>
            <tr>
                <td>br_time</td>
                <td>
                    <input type="text" name="br_time" size="80" value="<?php echo $this->br_time?>">
                </td>
            </tr>
            <?php
            $sql="select bs_id, bs_status from _bug_status order by bs_status";
            $options = $this->datacontrols->createOptionsFromQuery($sql, 0, 1, [], $this->bs_id, false, $this->cs);
            ?>
            <tr>
                <td>bs_id</td>
                <td>
                    <select name="bs_id">
                    <?php echo $options["list"]; ?>
                    </select>
                </td>
            </tr>
            <?php
            $sql="select usr_id, app_id from __user_app order by app_id";
            $options = $this->datacontrols->createOptionsFromQuery($sql, 0, 1, [], $this->usr_id, false, $this->cs);
            ?>
            <tr>
                <td>usr_id</td>
                <td>
                    <select name="usr_id">
                    <?php echo $options["list"]; ?>
                    </select>
                </td>
            </tr>
            <?php
            $sql="select app_id, doc_id from __app_document order by doc_id";
            $options = $this->datacontrols->createOptionsFromQuery($sql, 0, 1, [], $this->app_id, false, $this->cs);
            ?>
            <tr>
                <td>app_id</td>
                <td>
                    <select name="app_id">
                    <?php echo $options["list"]; ?>
                    </select>
                </td>
            </tr>
            <tr>
                <td align="center" colspan="2">
                    <input type="submit" name="action" value="<?php echo $this->action?>">
                    <?php   if($this->action!="Ajouter") { ?>
                    <input type="submit" name="action" value="Supprimer">
                    <?php   } ?>
                    <input type="reset" name="action" value="Annuler">
                    <input type="submit" name="action" value="Retour">
                </td>
            </tr>
        </table>
        </td>
    </tr>
</table>
</form>
<?php
}
?>