<?php
$pc = getArgument("pc");
$sr = getArgument("sr");
$curl_pager = "";
$dialog = "";
if(isset($pc)) $curl_pager="&pc=$pc";
if(isset($sr)) $curl_pager.="&sr=$sr";
if($this->query === "SELECT") {
    $sql = "select grp_id, grp_name from groups order by grp_id";
    $dbgrid = $this->datacontrols->createPagerDbGrid('groups', $sql, $this->page_id, "page.html", "&query=ACTION$curl_pager", "", true, true, $dialog, [0, 400], 15, $this->grid_colors, $this->cs);
    echo "<br>".$dbgrid;
} elseif($this->query === "ACTION") {
?>
<form method="POST" name="groupsForm" action="page.html?id=27&lg=fr">
<input type="hidden" name="query" value="ACTION">
<input type="hidden" name="event" value="onRun">
<input type="hidden" name="pc" value="<?php echo $pc?>">
<input type="hidden" name="sr" value="<?php echo $sr?>">
<input type="hidden" name="grp_id" value="<?php echo $this->grp_id?>">
<table border="1" bordercolor="<?php echo $this->panel_colors->border_color?>" cellpadding="0" cellspacing="0" witdh="100%" height="1">
<tr>
    <td align="center" valign="top" bgcolor="<?php echo $this->panel_colors->back_color?>">
        <table>
            <tr>
                <td>grp_id</td>
                <td>
                    <?php echo $this->grp_id?>
                </td>
            </tr>
            <tr>
                <td>grp_name</td>
                <td>
                    <textarea name="grp_name" cols="80" rows="8"><?php echo $this->grp_name?></textarea>
                </td>
            </tr>
            <tr>
                <td>grp_members_priv</td>
                <td>
                    <textarea name="grp_members_priv" cols="80" rows="8"><?php echo $this->grp_members_priv?></textarea>
                </td>
            </tr>
            <tr>
                <td>grp_menu_priv</td>
                <td>
                    <textarea name="grp_menu_priv" cols="80" rows="8"><?php echo $this->grp_menu_priv?></textarea>
                </td>
            </tr>
            <tr>
                <td>grp_page_priv</td>
                <td>
                    <textarea name="grp_page_priv" cols="80" rows="8"><?php echo $this->grp_page_priv?></textarea>
                </td>
            </tr>
            <tr>
                <td>grp_news_priv</td>
                <td>
                    <textarea name="grp_news_priv" cols="80" rows="8"><?php echo $this->grp_news_priv?></textarea>
                </td>
            </tr>
            <tr>
                <td>grp_items_priv</td>
                <td>
                    <textarea name="grp_items_priv" cols="80" rows="8"><?php echo $this->grp_items_priv?></textarea>
                </td>
            </tr>
            <tr>
                <td>grp_database_priv</td>
                <td>
                    <textarea name="grp_database_priv" cols="80" rows="8"><?php echo $this->grp_database_priv?></textarea>
                </td>
            </tr>
            <tr>
                <td>grp_images_priv</td>
                <td>
                    <textarea name="grp_images_priv" cols="80" rows="8"><?php echo $this->grp_images_priv?></textarea>
                </td>
            </tr>
            <tr>
                <td>grp_calendar_priv</td>
                <td>
                    <textarea name="grp_calendar_priv" cols="80" rows="8"><?php echo $this->grp_calendar_priv?></textarea>
                </td>
            </tr>
            <tr>
                <td>grp_newsletter_priv</td>
                <td>
                    <textarea name="grp_newsletter_priv" cols="80" rows="8"><?php echo $this->grp_newsletter_priv?></textarea>
                </td>
            </tr>
            <tr>
                <td>grp_forum_priv</td>
                <td>
                    <textarea name="grp_forum_priv" cols="80" rows="8"><?php echo $this->grp_forum_priv?></textarea>
                </td>
            </tr>
            <tr>
                <td>grp_users_priv</td>
                <td>
                    <textarea name="grp_users_priv" cols="80" rows="8"><?php echo $this->grp_users_priv?></textarea>
                </td>
            </tr>
            <tr>
                <td align="center" colspan="2">
                    <input type="submit" name="action" value="<?php echo $this->action?>">
                    <?php   if($this->action!="Ajouter") { ?>
                    <input type="submit" name="action" value="Supprimer">
                    <?php   } ?>
                    <input type="reset" name="action" value="Annuler">
                    <input type="submit" name="action" value="Retour">
                </td>
            </tr>
        </table>
        </td>
    </tr>
</table>
</form>
<?php
}
?>