#!/bin/bash
echo > /var/log/apache2/error_log
echo > /Users/david/Sites/CodePhoenix.net/SDK/php/SoL/logs/debug.log
echo > /Users/david/Sites/CodePhoenix.net/SDK/php/LAdmin/logs/debug.log
echo > /Users/david/Sites/CodePhoenix.net/SDK/php/Media/logs/debug.log
echo > /Users/david/Sites/CodePhoenix.net/SDK/php/Code-Phoenix.org/logs/debug.log
find /Users/david/Sites/CodePhoenix.net/SDK/php/SoL/runtime -type f -exec rm -f {} \; 
find /Users/david/Sites/CodePhoenix.net/SDK/php/SoL/web/js/runtime -type f -exec rm -f {} \; 
find /Users/david/Sites/CodePhoenix.net/SDK/php/LAdmin/runtime -type f -exec rm -f {} \; 
find /Users/david/Sites/CodePhoenix.net/SDK/php/Code-Phoenix.org/runtime -type f -exec rm -f {} \; 
find /Users/david/Sites/Media/runtime -type f -exec rm -f {} \; 
find /Users/david/Sites/Media/tmp -type f -exec rm -f {} \; 
rm -f /Users/david/Sites/Media/cache/main_html_artist_*; 
echo "All logs and temporary files cleared at "$(date) 
exit 0

